# -*- coding: utf-8 -*-
"""funciones_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1elmPMf1GYZ8H_QtgPdYcQ476Cx50sJOO

# 1. Funciones


En esta sección se retoma la el concepto de funciones que son bloques de códigos que están desieñados para hacer un trabajo específico. Una vez que se desea reaizar una tarea que ya ha sido desarrollada dentro de función, simplemente se tiene que mandar a llamar o invocar a la función.

En esta sección también se muestra cómo mandar información a una funcion diseñanada para procesar datos y  regresar algún valor o ejecutar algún comando. 

Finalmente se muestra como almacenar funciones en archivos separados llamandos *módulos* que ayudan a organizar mejor el programa principal.

## 1.1. Definiendo una función ##

Aquí se muestra un ejemplo de una función llamada $\verb|greet_user|$ que simplemente imprime en la terminal una saludo
"""

########################################
# CELDA 1 : Definición de una función  #
########################################


# Esta es la definición de una función
def greet_user():
    """Mostrar un simple saludo."""
    print("Hola!")


# Ya estamos fuera de la función y se mandará a llamar
greet_user()

"""En este ejemplo se muestra la estructura más simple de una fucnión . En la línea $\verb|1|$ se utiliza la palabra reservada $\verb|def|$ para notificar al intérprete de Python que comienza una función, seguido de $\verb|def|$ sigue el nombre de la función y después unos parétesis vacíos, estos paréntesis vacíos implican que la fución no recibe ninguna información par poder trabajar, después de los paréntesis van dos puntos, estos indican que el código que sigue a continuación es el cuerpo de la función. Observe que todas las líneas de código pertenecientes a la fución deben de guardar la misma sangría. 


### 1.1.1 Pasando información a la función

La función anterior sólo puede decir Hola, a continuación se muestra una modificación a la función para que ésta pueda mostrar un saludo personalizado.
"""

#########################################
# CELDA 2 : Paso de info a la función   #
#########################################


# Esta es la definición de una función 
def greet_user(username):
    """ Mostrar un saludo personalizado"""
    print("Hola "+username.title()+"!")
    
#Ya estamos fuera de la función y se mandará a llamar
greet_user("Juan Pérez")

"""### 1.1.2 Ejercicios

#### 1.1.2.1.Mensaje.
Escriba una función llamanda $\verb|display_message()|$ que imprima en la pantalla un mensaje que indique los temas que se han visto hasta el momento.

#### 1.1.2.2 Libro favorito.
Escriba una función que se llame $\verb|libro_favorito()|$ que acepte un parámetro llamado $\verb|titulo|$ y que despligue en la terminal *Tu libro favorito es (nombre del libro)*
"""

"EJERCICIO 1.1.2.1 MENSAJE"
# Temas vistos en clase
def display_message():
    print("Estos son algunos temas vistos y repasados en clase: Operadores lógicos, condicionales, tipos de datos, modulos, listas, funciones, clases etc.")

    
#Se mandará a llamar
display_message()

"EJERCICIO 1.1.2.2 LIBRO FAVORITO"
#Libros
libro_favorito = str(input('¿Cuál es tú libro favorito?: '))
 def libro_favorito(libro_fav):
    # c= (f"Tú libro favorito es: {r} ")

from google.colab import drive
drive.mount('/content/drive')

"""## 1.2. Paso de argumentos

En ocasiones una fución necesita múltiples parámetros, dentro de Python existen diferentes maneras de pasar los argumentos a una función, el uso y la implementación dependerá de la necesidad del usuario y programador.

### 1.2.1 Argumentos Posicionales

Ejecute las siguientes celdas y observe los resultados
"""

#########################################
# CELDA 3 : Descripción de mascota      #
#########################################


def descripcion_mascota(tipo_animal, nombre):
    """Muestra la información de una mascota."""
    print("\nTengo un(a) " + tipo_animal + " como mascota.")
    print("Mi " + tipo_animal +  " se llama " + nombre)

#########################################
# CELDA 4 :                             #
#########################################


descripcion_mascota("perro","Filemon")

#########################################
# CELDA 5 :                             #
#########################################


descripcion_mascota("Michi","gato")

"""La función se llama $\verb|descripcion_mascota|$ y se puede observar en su implementación en la *celda 3* observe que recibe dos parámetros que deben de ser de tipo *string*, e imprime la información referente a mascota, en la *celda 4 y 5* se manda a llamar la función y si se observa el resultado de la celda 4 los enunciados muestran coherencia, mientras que en la celda 5 son incoherentes. 

La diferncia entre las celdas fue el orden de los argumentos, en la celda 4 "perro" lo asinga a "tipo de animal" y "Filemon" lo asigna a nombre, mientras que en la celda 5 "Michi" lo asigna "tipo de animal", mientras que "gato" lo asinga a "nombre".

A esta forma de mandar los parámetros en los que es de gran importancia el orden en que se mandan los mismos, se le conoce como **Argumentos posicionales**

### 1.2.2 Argumentos "Keyword"

Ejecute la *celda 3* y depués las *celda 6 y 7*
"""

#########################################
# CELDA 6 :                             #
#########################################


descripcion_mascota(tipo_animal = "hamster",nombre = "Harry")

#########################################
# CELDA 7 :                             #
#########################################


descripcion_mascota(nombre = "Cuco",tipo_animal = "Hurón")

"""Observe que ahora el orden de los argumentos no importa, esto se debe a que desde que se manda a llamar la función se hace la asignación a los variables locales de la función. Es de gran importancia que note que la implementación de la función no cambió en nada, los cambios se deben de hacer al momento de llamar la función.

## 1.2.3 Valores predeterminados

En la definición de las funciones se puede definir valores predeterminados para los parámetros. Si un parámetro se manda desde la llamada de la función Python utiliza el valor que se ha mandado en la invocación de la función y deshecha el predeterminado, sino se ha manda el parámetro desde la llamada de la función entonces se utilizará el valor predeterminado. Observe el código de las celda 8 y ejecute la celda para observar el comportamiento de la misma.
"""

#########################################
# CELDA 8 : Valores predeterminados     #
#########################################
def descripcion_mascota(nombre,tipo_animal = "perro"):
    """Muestra la información de una mascota"""
    print("\nUsted tiene un@ " + tipo_animal +"." )
    print("Mi " + tipo_animal + " se llama " + nombre.title() +".")

descripcion_mascota(nombre="Orejas")

"""## 1.3 Ejercicios

### 1.3.1 Playera

Escriba una función llamanda $\verb|hacerPlayera()|$ que acepte como argumento, el tamaño y un texto que apararecerá cerigrafeado en la playera. La función deberá imprimir en la terminal algo parecido a lo siguiente

*La playera es talla "Grande" y el texto a cerigrafear es: "Hola amigos"*

Para verificar el correcto funcionamiento de la función, genere un programa que la invoque.
"""

####  Prgrama de Playeras  ###
def hacerPlayera(talla,cerigraf= "Hola amigos"):
   """Muestra talla y estampado de una playera"""
   print("\nLa playera es " + talla +"." )
   print("Y el texto a cerigrafear es " + cerigraf +".")

  
hacerPlayera(talla="Grande")

"""### 1.3.2 Playeras Grandes

Modique la función $\verb|hacerPlayera()|$ de tal manera que las playeras grandes sean predeterminadas y el texto predefinido para la cerigrafear sea $\verb|yo <3 Python|$.

Para verificar el correcto funcionamiento del módulo:

1. Genere una playera grande utlizando el texto predeterminado.

2. Genere una playera mediana con el texto predeterminado.

3. Genere una playera de talla distnta a grande con un texto distinto al predeterminado.
"""

#@title Texto de título predeterminado
###    Programa de Playeras grandes ###
def hacerPlayera(talla,cerigraf= "Yo <3 Python"):

   """Muestra talla y cerigrafia de la playera"""

   print("\nLa playera es " + talla +"." )
   print("Y el texto a cerigrafear es " + cerigraf +".")

   print("\nLa playera es Chica" )
   print("Y el texto a cerigrafear es  I Love Rock'n Roll")

hacerPlayera(talla="Grande")
hacerPlayera(talla="Mediana") 
#hacerPlayera(talla="Chica")

"""### 1.3.2 Países y ciudades

Escriba una función llamada $\verb|descripcionCiudad()|$ que acepte como argumentos el nombre de una ciudad y el nombre de un país como argumentos y que imprima en la terminal un texto como: *Xalapa está en México*, *Río de Janeiro está en Brazil*, *París está en Fracia*. Ponga como valor predeterminado "México" a la variable país, y llame a la función tres veces donde por lo menos una ciudad no pertenezca al país México.
"""

def descripcionCiudad(city,país = Mexico):
    """Muestra datos geográficos"""
    print("\nXalapa esta en México " + tipo_animal +"." )
    print("Mi " + tipo_animal + "Río de Janeiro esta en Brasil " + nombre.title() +".")



  descripcionCiudad(city,país)

"""## 1.4 Valores de regreso

## 1.4.1 Introducción.
Una función no necesariamente tiene que imprimir texto o mostrar la información que recibe, usualmente, existen funciones que reciben argumentos, los procesan y después regresan al programa principal el o los datos modificados, a éstos datos que la función regresa al programa principal se le conoce como **valor de regreso** o **valor de retorno**, observe el código de la siguiente celda y su comportamiento, en la que se calcula el volumen de un cubo.
"""

def volumenCubo(longitud_lado):
    volumen = longitud_lado**3
    return volumen

print("El volumen de un cubo cuyos lados miden 4cm es: " + str(volumenCubo(4)) + " cm^3")

"""Observe que la función $\verb|volumenCubo(longitud_lado):|$ recibe como argumento un número y dentro de la función eleva ese valor al cubo y lo asigna a la variable local $\verb|volumen|$ y regresa el valor guardado en $\verb|volumen|$

## 1.5 Almacenando Funciones en Módulo

Una ventaja de las funciones es que se pueden almacenar en archivos distintos de tal manera que el archivo principal no esté tan extenso y sea más sencillo de dar mantenimiento y poder depurar los errores, en otros lenguajes de programación como en C y C++ es equivalente las ilbrerías creadas por los usuarios.

En la siguiente celda se muestra un ejemplo de una librería en la que se calcula el área y perímetro de la cara de un cubo, el área, perímetro y volumen de un cubo.

####       cubo.py     ####
def cara_area(lado):
	return lado**2

def cara_perimetro(lado):
	return lado*4

def perimetro(lado):
	return lado*12

def volumen(lado):
	return lado**3

def area(lado):
	return cara_area(lado)*6

Para agregar una sóla función del módulo que se llama $\verb|cubo.py|$ sólo basta poner al inicio la siguiente directiva:

$\verb|from cubo import cara_area|$
"""

from cubo import cara_area

print("El área de la cara de un cubo cuyo lado es 2 cm es: " + str(cara_area(2)))

"""Para agregar todo el módulo, se pueden agregar todas las funciones una por una, sin embargo, si el módulo tiene muchas funciones no resulta muy práctico, para poder agregar todo el módulo se debe de agregar la siguiente directiva

$\verb|from cubo import *|$
"""

from cubo import *

print("El área de la cara de un cubo cuyo lado es 2 cm es: " + str(cara_area(2)))

print("El perímetro de la cara de un cubo de lado de 2cm por lado es: " + str(cara_perimetro(2)))

print("El perímetro de un cubo cuyos lados miden 3 cm es:  " + str(perimetro(3)))

print("El área de un cubo cuyos lados miden 3 cm es: " + str(area(3)))

print("El volumen de un cubo cuyos lados miden 3 cm es: " + str(volumen(3)))

"""## 1.6 Ejercicios

1. Hacer un módulo con las funciones básicas para una calculadora, suma, resta, producto y división, en la función de división si el denomidador es igual a cero debe de volver a leer el valor del denominador hasta que sea distinto de cero (se recomienda utilizar el ciclo while y el condicional if)

2. Hacer una función que el usuario introduzca un número y la función debe de desplegar un triángulo de sumas, *Como ejemplo, si el usuario manda  a la función 4 debeía imprimir el siguiente arreglo*

+

++

+++

++++
"""

